"""Inline browser Canvas renderer used by the standalone report HTML."""

from __future__ import annotations


PNG_SCRIPT = r'''const PNG_REPORT=JSON.parse(document.getElementById('png-report').textContent);const W=1240,MIN_H=1754,SCALE=2,M=82,GREEN='#56FFA3',TEXT='#F2F6F3',SECONDARY='rgba(242,246,243,.70)',META='rgba(242,246,243,.42)',LINE='rgba(242,246,243,.14)',BG='#080B09';const SAFE_LEFT=M,SAFE_RIGHT=W-M,SAFE_TOP=24,SAFE_BOTTOM=40;const UI='"Noto Sans CJK SC","Microsoft YaHei","PingFang SC",sans-serif';const MONO='"IBM Plex Mono","Noto Sans CJK SC","Microsoft YaHei",monospace';const CJK_PUNCTUATION='，。！？；：、）》」』】”’…';
function measureWrappedLines(ctx,text,maxWidth,font,lineHeight=1,maxLines=null){if(!Number.isFinite(maxWidth)||maxWidth<=0)throw new Error('PNG_LAYOUT_SAFE invalid text width');ctx.font=font;const chars=Array.from(String(text??''));const wrapped=[];let line='';for(const char of chars){const candidate=line+char;if(line&&ctx.measureText(candidate).width>maxWidth){if(CJK_PUNCTUATION.includes(char)){const parts=Array.from(line);const carry=parts.pop()||'';const kept=parts.join('');if(kept)wrapped.push(kept);line=carry+char}else{wrapped.push(line);line=char}}else line=candidate}if(line)wrapped.push(line);const widths=wrapped.map(item=>ctx.measureText(item).width);if(maxLines!==null&&wrapped.length>maxLines)throw new Error(`PNG_LAYOUT_SAFE ${maxLines} line limit exceeded`);return{lines:wrapped,width:Math.max(0,...widths),height:wrapped.length*lineHeight,lineHeight};}
function lines(ctx,text,width){return measureWrappedLines(ctx,text,width,ctx.font,1).lines}
function textBlock(ctx,text,x,y,width,font,lineHeight,color,draw=true){const measured=measureWrappedLines(ctx,text,width,font,lineHeight);if(draw)measured.lines.forEach((line,index)=>ctx.fillText(line,x,y+index*lineHeight));return y+measured.height}
function safeBlock(name,left,top,right,bottom,nextY,children=[]){return{name,left,top,right,bottom,nextY,children};}
function assertSafeBlock(block,canvasHeight){if(!block)return;if(![block.left,block.top,block.right,block.bottom].every(Number.isFinite)||block.left<SAFE_LEFT-0.5||block.right>SAFE_RIGHT+0.5||block.top<SAFE_TOP-0.5||block.bottom>canvasHeight-SAFE_BOTTOM+0.5||block.left>block.right||block.top>block.bottom)throw new Error(`PNG_LAYOUT_SAFE ${block.name} bounds ${JSON.stringify(block)}`);(block.children||[]).forEach(child=>assertSafeBlock(child,canvasHeight));}
function drawHeader(ctx,y,draw=true){if(draw){ctx.font=`700 20px ${UI}`;ctx.fillStyle=GREEN;ctx.beginPath();ctx.arc(M+6,y-6,6,0,Math.PI*2);ctx.fill();ctx.fillText('Ayu',M+28,y);ctx.fillStyle=TEXT;ctx.fillText(' Running',M+64,y);ctx.font=`600 17px ${UI}`;ctx.fillStyle=META;const right=`COROS MCP 已同步 · ${PNG_REPORT.date_display}`;ctx.fillText(right,W-M-ctx.measureText(right).width,y)}if(draw)divider(ctx,y+34);return safeBlock('Header',M,y-20,W-M,y+34,y+76)}
function divider(ctx,y){ctx.strokeStyle=LINE;ctx.beginPath();ctx.moveTo(M,y);ctx.lineTo(W-M,y);ctx.stroke()}
function headlineParts(text){for(const delimiter of ['，','；','。',',',';']){if(!text.includes(delimiter))continue;const pair=text.split(delimiter,2);if(pair[0].trim()&&pair[1].trim())return[pair[0].trim()+delimiter,pair[1].trim()]}const chars=Array.from(text);return chars.length>6?[chars.slice(0,-3).join(''),chars.slice(-3).join('')]:[text]}
function layoutScore(ctx,y,draw=true){const score=PNG_REPORT.score;if(!score)return null;const titleWidth=760,scoreLeft=M+titleWidth+72,scoreRight=SAFE_RIGHT,scoreColumnWidth=scoreRight-scoreLeft,dotWidth=10,dotGap=12;const valueFont=`800 58px ${MONO}`,maximumFont=`700 22px ${MONO}`,stateFont=`500 17px ${UI}`,stateLineHeight=28;ctx.font=valueFont;const valueWidth=ctx.measureText(String(score.value??'')).width;ctx.font=maximumFont;const maximumWidth=ctx.measureText(String(score.maximum??'')).width;const scoreLineWidth=valueWidth+8+maximumWidth;const scoreLineLeft=scoreRight-scoreLineWidth;if(scoreLineLeft<scoreLeft)throw new Error('PNG_LAYOUT_SAFE score value exceeds score column');const state=[score.status,score.training_type].filter(Boolean).join(' · ');const stateX=scoreLeft+dotWidth+dotGap,stateWidth=scoreRight-stateX;const measured=measureWrappedLines(ctx,state,stateWidth,stateFont,stateLineHeight);if(measured.width>stateWidth+0.5)throw new Error('PNG_LAYOUT_SAFE score state measured width exceeds score column');const scoreTop=y-50,stateTop=y+46,stateBottom=stateTop+measured.height,bottom=Math.max(y+26,stateBottom);if(draw){ctx.font=valueFont;ctx.fillStyle=TEXT;ctx.fillText(score.value,scoreLineLeft,y+12);ctx.font=maximumFont;ctx.fillStyle=GREEN;ctx.fillText(score.maximum,scoreLineLeft+valueWidth+8,y+12);ctx.fillStyle=GREEN;ctx.beginPath();ctx.arc(scoreLeft+dotWidth/2,stateTop+8,dotWidth/2,0,Math.PI*2);ctx.fill();ctx.font=stateFont;ctx.fillStyle=SECONDARY;measured.lines.forEach((line,index)=>ctx.fillText(line,stateX,stateTop+18+index*stateLineHeight))}const block=safeBlock('Score',scoreLeft,scoreTop,scoreRight,bottom,bottom,[]);block.lines=measured.lines.length;block.statusText=state;block.textWidth=measured.width;block.textMaxWidth=stateWidth;return block}
function drawHero(ctx,y,draw=true){const titleWidth=PNG_REPORT.score?760:W-M*2;ctx.font=`900 66px ${UI}`;const parts=headlineParts(PNG_REPORT.headline);const titleLines=parts.flatMap((part,partIndex)=>measureWrappedLines(ctx,part,titleWidth,`900 66px ${UI}`,70).lines.map(line=>({line,accent:partIndex>0})));if(draw)titleLines.forEach((item,index)=>{ctx.fillStyle=item.accent?GREEN:TEXT;ctx.fillText(item.line,M,y+index*70)});const scoreBlock=layoutScore(ctx,y,draw);let next=y+titleLines.length*70+28;ctx.font=`500 22px ${UI}`;ctx.fillStyle=SECONDARY;next=textBlock(ctx,PNG_REPORT.subtitle,M,next,titleWidth,`500 22px ${UI}`,34,SECONDARY,draw);const contentBottom=Math.max(next,scoreBlock?scoreBlock.bottom:next);if(draw)divider(ctx,contentBottom+30);return safeBlock('Hero',M,y-66,W-M,contentBottom+30,contentBottom+96,scoreBlock?[scoreBlock]:[])}
function drawMetrics(ctx,y,draw=true){const items=PNG_REPORT.primary_metrics||[];const width=(W-M*2)/Math.max(items.length,1);if(draw)items.forEach((item,index)=>{const x=M+index*width;const inset=index?18:0;if(index){ctx.strokeStyle=LINE;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+70);ctx.stroke()}ctx.font=`500 14px ${UI}`;ctx.fillStyle=META;ctx.fillText(item.label,x+inset,y+17);ctx.font=`700 22px ${MONO}`;ctx.fillStyle=TEXT;ctx.fillText(item.value,x+inset,y+52)});if(draw)divider(ctx,y+96);return safeBlock('Metrics',M,y,W-M,y+96,y+132)}
function drawToday(ctx,y,draw=true){if(draw){ctx.font=`800 18px ${UI}`;ctx.fillStyle=GREEN;ctx.fillText('TODAY 今日结论',M,y)}let next=y+48;ctx.font=`800 34px ${UI}`;ctx.fillStyle=TEXT;next=textBlock(ctx,PNG_REPORT.today.headline,M,next,W-M*2,`800 34px ${UI}`,46,TEXT,draw);next+=10;ctx.font=`500 21px ${UI}`;ctx.fillStyle=SECONDARY;next=textBlock(ctx,PNG_REPORT.today.explanation,M,next,W-M*2,`500 21px ${UI}`,34,SECONDARY,draw);if(draw)divider(ctx,next+38);return safeBlock('Today',M,y,W-M,next+38,next+76)}
function bulletColumn(ctx,title,items,x,y,width,draw=true){if(draw){ctx.font=`800 17px ${UI}`;ctx.fillStyle=GREEN;ctx.fillText(title,x,y)}let next=y+38;ctx.font=`500 19px ${UI}`;for(const item of items||[]){const wrapped=lines(ctx,item,width-28);if(draw){ctx.fillStyle=GREEN;ctx.beginPath();ctx.arc(x+4,next-6,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=SECONDARY;wrapped.forEach((line,index)=>ctx.fillText(line,x+22,next+index*31))}next+=wrapped.length*31+15}return next}
function drawOutputCost(ctx,y,draw=true){const gap=56,width=(W-M*2-gap)/2;const left=bulletColumn(ctx,'OUTPUT 做得好的地方',PNG_REPORT.output,M,y,width,draw);const right=bulletColumn(ctx,'COST 当前观察点',PNG_REPORT.cost,M+width+gap,y,width,draw);const next=Math.max(left,right);if(draw)divider(ctx,next+28);return safeBlock('OutputCost',M,y,W-M,next+28,next+66)}
function drawLoad(ctx,y,draw=true){if(draw){ctx.font=`800 18px ${UI}`;ctx.fillStyle=GREEN;ctx.fillText('LOAD 近期负荷',M,y)}let next=y+46;ctx.font=`800 32px ${UI}`;ctx.fillStyle=TEXT;if(PNG_REPORT.load.headline)next=textBlock(ctx,PNG_REPORT.load.headline,M,next,720,`800 32px ${UI}`,43,TEXT,draw);next+=24;const metrics=PNG_REPORT.load.metrics||[];if(draw)metrics.forEach((item,index)=>{const x=M+index*210;ctx.font=`500 14px ${UI}`;ctx.fillStyle=META;ctx.fillText(item.label,x,next);ctx.font=`700 24px ${MONO}`;ctx.fillStyle=TEXT;ctx.fillText(item.value,x,next+34)});let contentBottom=next+76;if(PNG_REPORT.load.status){const statusX=M+706,statusWidth=SAFE_RIGHT-statusX,statusTop=next+6;const statusMeasured=measureWrappedLines(ctx,PNG_REPORT.load.status,statusWidth,`500 21px ${UI}`,28);if(draw){ctx.fillStyle=GREEN;ctx.beginPath();ctx.arc(M+690,next+25,5,0,Math.PI*2);ctx.fill();ctx.font=`500 21px ${UI}`;ctx.fillStyle=GREEN;statusMeasured.lines.forEach((line,index)=>ctx.fillText(line,statusX,statusTop+22+index*28))}contentBottom=Math.max(contentBottom,statusTop+statusMeasured.height)}if(draw&&PNG_REPORT.load.recovery_percent){ctx.font=`800 56px ${MONO}`;ctx.fillStyle=TEXT;ctx.fillText(PNG_REPORT.load.recovery_percent,W-M-150,next+25);ctx.font=`700 22px ${MONO}`;ctx.fillStyle=GREEN;ctx.fillText('%',W-M-65,next+25)}if(draw)divider(ctx,contentBottom+28);return safeBlock('Load',M,y,W-M,contentBottom+28,contentBottom+66)}
function drawTomorrow(ctx,y,draw=true){if(!PNG_REPORT.tomorrow)return safeBlock('Tomorrow',M,y,W-M,y,y);if(draw){ctx.font=`800 18px ${UI}`;ctx.fillStyle=GREEN;ctx.fillText('TOMORROW 明日课表',M,y)}let next=y+48;const plan=PNG_REPORT.tomorrow.schedule;ctx.font=`800 32px ${UI}`;ctx.fillStyle=TEXT;next=textBlock(ctx,`明日课表：${plan.title||''}`,M,next,W-M*2,`800 32px ${UI}`,43,TEXT,draw)+15;ctx.font=`900 58px ${UI}`;ctx.fillStyle=GREEN;next=textBlock(ctx,plan.title||'',M,next,W-M*2,`900 58px ${UI}`,66,GREEN,draw)+18;const metrics=plan.metrics||[];if(draw)metrics.forEach((item,index)=>{const x=M+index*250;ctx.font=`500 14px ${UI}`;ctx.fillStyle=META;ctx.fillText(item.label,x,next);ctx.font=`700 24px ${MONO}`;ctx.fillStyle=TEXT;ctx.fillText(item.value,x,next+34)});next+=78;ctx.font=`500 20px ${UI}`;ctx.fillStyle=SECONDARY;next=textBlock(ctx,PNG_REPORT.tomorrow.context||'',M,next,W-M*2,`500 20px ${UI}`,32,SECONDARY,draw);if(draw)divider(ctx,next+34);return safeBlock('Tomorrow',M,y,W-M,next+34,next+72)}
function runPngLayoutPreflight(ctx){const blocks=[];let y=62;let block=drawHeader(ctx,y,false);blocks.push(block);y=block.nextY;block=drawHero(ctx,y,false);blocks.push(block);y=block.nextY;block=drawMetrics(ctx,y,false);blocks.push(block);y=block.nextY;block=drawToday(ctx,y,false);blocks.push(block);y=block.nextY;block=drawOutputCost(ctx,y,false);blocks.push(block);y=block.nextY;block=drawLoad(ctx,y,false);blocks.push(block);y=block.nextY;block=drawTomorrow(ctx,y,false);if(block.bottom>block.top)blocks.push(block);y=block.nextY;const logicalHeight=Math.max(MIN_H,Math.ceil(y+72));blocks.forEach(item=>assertSafeBlock(item,logicalHeight));return{blocks,logicalHeight,nextY:y}}
function drawBackground(ctx,logicalHeight){ctx.fillStyle=BG;ctx.fillRect(0,0,W,logicalHeight);ctx.strokeStyle='rgba(86,255,163,.026)';ctx.lineWidth=1;for(let gx=0;gx<W;gx+=90){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,logicalHeight);ctx.stroke()}for(let gy=0;gy<logicalHeight;gy+=90){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(W,gy);ctx.stroke()}}
async function downloadPng(){if(document.fonts&&document.fonts.ready)await document.fonts.ready;const measure=document.createElement('canvas').getContext('2d');const layout=runPngLayoutPreflight(measure);window.__ayuPngLayoutAudit={status:'PASS',hasScore:Boolean(PNG_REPORT.score),width:W*SCALE,height:layout.logicalHeight*SCALE,blocks:layout.blocks.map(block=>({name:block.name,left:block.left,top:block.top,right:block.right,bottom:block.bottom})),score:layout.blocks.flatMap(block=>block.children||[]).find(block=>block.name==='Score')||null};const canvas=document.createElement('canvas');canvas.width=W*SCALE;canvas.height=layout.logicalHeight*SCALE;const ctx=canvas.getContext('2d');ctx.scale(SCALE,SCALE);drawBackground(ctx,layout.logicalHeight);let y=62;let block=drawHeader(ctx,y,true);y=block.nextY;block=drawHero(ctx,y,true);y=block.nextY;block=drawMetrics(ctx,y,true);y=block.nextY;block=drawToday(ctx,y,true);y=block.nextY;block=drawOutputCost(ctx,y,true);y=block.nextY;block=drawLoad(ctx,y,true);y=block.nextY;block=drawTomorrow(ctx,y,true);y=block.nextY;assertSafeBlock(block,layout.logicalHeight);canvas.toBlob(blob=>{if(!blob)throw new Error('PNG export returned no blob');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Ayu_Running_${PNG_REPORT.date}.png`;a.click();URL.revokeObjectURL(url)},'image/png')}
window.__ayuPngLayoutAudit={status:'NOT_RUN'};document.getElementById('download-png').addEventListener('click',downloadPng);const links=[...document.querySelectorAll('.nav a')],sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+entry.target.id))}),{rootMargin:'-25% 0px -60% 0px',threshold:0});sections.forEach(section=>observer.observe(section));'''
